/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Lahiruka
 */
public class ViewExpenses extends javax.swing.JFrame {

    /**
     * Creates new form ViewExpenses
     */
    public ViewExpenses() {
        initComponents();
        showDate();
        showTime();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        labelDate.setText(s.format(d));

    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                labelTime.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reload = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        expensesTable = new javax.swing.JTable();
        lblFood = new javax.swing.JLabel();
        lblTransportation = new javax.swing.JLabel();
        lblStationary = new javax.swing.JLabel();
        lblUtility = new javax.swing.JLabel();
        lblLoans = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        txtTransport = new javax.swing.JTextField();
        txtFood = new javax.swing.JTextField();
        txtStationary = new javax.swing.JTextField();
        txtLoan = new javax.swing.JTextField();
        txtUtility = new javax.swing.JTextField();
        txtOther = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCalcTot = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtExpenseID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelLogout = new javax.swing.JLabel();
        labelHome = new javax.swing.JLabel();
        labelAnalitics = new javax.swing.JLabel();
        labelAddExpense = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(974, 535));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reload.setBackground(new java.awt.Color(51, 102, 255));
        reload.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        reload.setForeground(new java.awt.Color(255, 255, 255));
        reload.setText("Reload");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        getContentPane().add(reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, 25));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 93, -1));

        expensesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ExpenseID", "Date", "TimeStamp", "Food", "Transport", "Stationary", "Utility Bills", "Loan Installments", "Other"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        expensesTable.setMinimumSize(new java.awt.Dimension(1087, 454));
        jScrollPane1.setViewportView(expensesTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 954, 185));

        lblFood.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFood.setText("Food");
        getContentPane().add(lblFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lblTransportation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTransportation.setText("Transport");
        getContentPane().add(lblTransportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        lblStationary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStationary.setText("Stationaries");
        getContentPane().add(lblStationary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        lblUtility.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUtility.setText("Utility_Bills");
        getContentPane().add(lblUtility, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 83, -1));

        lblLoans.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLoans.setText("Loans");
        getContentPane().add(lblLoans, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 53, -1));

        lblOther.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOther.setText("Other");
        getContentPane().add(lblOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 52, -1));
        getContentPane().add(txtTransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 181, -1));
        getContentPane().add(txtFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 181, -1));
        getContentPane().add(txtStationary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 181, -1));
        getContentPane().add(txtLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 181, -1));
        getContentPane().add(txtUtility, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 181, -1));
        getContentPane().add(txtOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 181, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total Exp");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 79, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 181, -1));

        btnCalcTot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalcTot.setText("Calculate");
        btnCalcTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcTotActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 85, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 85, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Enter Relevent ExpenseID to delete any expense. ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        getContentPane().add(txtExpenseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 181, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ExpenseID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 412, 180, 0));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Expenses");

        labelLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLogout.setForeground(new java.awt.Color(204, 0, 0));
        labelLogout.setText("Logout");
        labelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoutMouseClicked(evt);
            }
        });

        labelHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHome.setForeground(new java.awt.Color(0, 0, 204));
        labelHome.setText("Home");
        labelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHomeMouseClicked(evt);
            }
        });

        labelAnalitics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAnalitics.setForeground(new java.awt.Color(0, 153, 0));
        labelAnalitics.setText("Analitics");
        labelAnalitics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAnaliticsMouseClicked(evt);
            }
        });

        labelAddExpense.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAddExpense.setText("Add Expense");
        labelAddExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddExpenseMouseClicked(evt);
            }
        });

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDate.setText("Today");

        labelTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTime.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAddExpense)
                .addGap(10, 10, 10)
                .addComponent(labelAnalitics)
                .addGap(14, 14, 14)
                .addComponent(labelHome)
                .addGap(9, 9, 9)
                .addComponent(labelLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDate)
                    .addComponent(labelTime)
                    .addComponent(labelAddExpense)
                    .addComponent(labelAnalitics)
                    .addComponent(labelHome)
                    .addComponent(labelLogout)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        String SQL = "Select * From expenses";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/budgetpal", "root", "1234");
            PreparedStatement stm = connection.prepareStatement(SQL);
            ResultSet rst = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) expensesTable.getModel();
            dtm.setRowCount(0);
            while (rst.next()) {
                Object[] rowData = {rst.getInt("Eid"), rst.getString("Date"), rst.getString("TimeStamp"), rst.getDouble("Food"), rst.getDouble("Transport"), rst.getDouble("Stationaries"), rst.getDouble("Utility_Bills"), rst.getDouble("Loans"), rst.getDouble("Other")};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_reloadActionPerformed

    private void labelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelLogoutMouseClicked

    private void labelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHomeMouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelHomeMouseClicked

    private void labelAnaliticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAnaliticsMouseClicked
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/budgetpal", "root", "1234");
            String query = "SELECT expType,expAmount FROM totalExp";

            DefaultPieDataset pieDataset = new DefaultPieDataset();

            PreparedStatement stm = connection.prepareStatement(query);
            ResultSet rst = stm.executeQuery();

            String Expense_Type;
            int Expense_Amount;

            while (rst.next()) {
                Expense_Type = rst.getString("expType");
                Expense_Amount = rst.getInt("expAmount");
                pieDataset.setValue(Expense_Type, new Integer(Expense_Amount));
            }

            JFreeChart chart = ChartFactory.createPieChart("My Expenses", pieDataset, true, true, true);
            PiePlot p = (PiePlot) chart.getPlot();

            ChartFrame frame = new ChartFrame("My Expenses", chart);
            frame.setVisible(true);
            frame.setSize(600, 500);

                        
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelAnaliticsMouseClicked

    private void labelAddExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddExpenseMouseClicked
        //go to add expense page
        new addExpense().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAddExpenseMouseClicked

    private void btnCalcTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcTotActionPerformed
        try {
            // connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/budgetpal", "root", "1234");
            //get sum of food column
            String SQL = "Select SUM(Food) from expenses";
            PreparedStatement stm = connection.prepareStatement(SQL);
            ResultSet rst = stm.executeQuery();
            if (rst.next()) {
                txtFood.setText(rst.getString("SUM(Food)"));
            }
            //get sum of transport column
            String SQL2 = "Select SUM(Transport) from expenses";
            PreparedStatement stm2 = connection.prepareStatement(SQL2);
            ResultSet rst2 = stm2.executeQuery();
            if (rst2.next()) {
                txtTransport.setText(rst2.getString("SUM(Transport)"));
            }
            //get sum of stationaries table
            String SQL3 = "Select SUM(Stationaries) from expenses";
            PreparedStatement stm3 = connection.prepareStatement(SQL3);
            ResultSet rst3 = stm3.executeQuery();
            if (rst3.next()) {
                txtStationary.setText(rst3.getString("SUM(Stationaries)"));
            }
            //get sum of Utility bills table
            String SQL4 = "Select SUM(Utility_Bills) from expenses";
            PreparedStatement stm4 = connection.prepareStatement(SQL4);
            ResultSet rst4 = stm4.executeQuery();
            if (rst4.next()) {
                txtUtility.setText(rst4.getString("SUM(Utility_Bills)"));
            }
            //get sum of loans column
            String SQL5 = "Select SUM(Loans) from expenses";
            PreparedStatement stm5 = connection.prepareStatement(SQL5);
            ResultSet rst5 = stm5.executeQuery();
            if (rst5.next()) {
                txtLoan.setText(rst5.getString("SUM(Loans)"));
            }
            //get sum of other table
            String SQL6 = "Select SUM(Other) from expenses";
            PreparedStatement stm6 = connection.prepareStatement(SQL6);
            ResultSet rst6 = stm6.executeQuery();
            if (rst6.next()) {
                txtOther.setText(rst6.getString("SUM(Other)"));
            }
            ////calculation of total expense
            double food = Double.parseDouble(txtFood.getText());
            double transport = Double.parseDouble(txtTransport.getText());
            double stationary = Double.parseDouble(txtStationary.getText());
            double utility = Double.parseDouble(txtUtility.getText());
            double loan = Double.parseDouble(txtLoan.getText());
            double other = Double.parseDouble(txtOther.getText());
            double y = (food + transport + stationary + utility + loan + other);
            String x = Double.toString(y);
            txtTotal.setText(x);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnCalcTotActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // add to total expenses table
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/budgetpal", "root", "1234");

            String SQL = "Update totalexp set Date =?, expAmount=? WHERE expType=?";

            //update food row
            PreparedStatement stm = connection.prepareStatement(SQL);
            stm.setObject(1, labelDate.getText());
            stm.setObject(3, lblFood.getText());
            stm.setObject(2, txtFood.getText());
            int res = stm.executeUpdate();
            //update transportation row
            PreparedStatement stm2 = connection.prepareStatement(SQL);
            stm2.setObject(1, labelDate.getText());
            stm2.setObject(3, lblTransportation.getText());
            stm2.setObject(2, txtTransport.getText());
            int res2 = stm2.executeUpdate();
            //update stationary row
            PreparedStatement stm3 = connection.prepareStatement(SQL);
            stm3.setObject(1, labelDate.getText());
            stm3.setObject(3, lblStationary.getText());
            stm3.setObject(2, txtStationary.getText());
            int res3 = stm3.executeUpdate();
            //update Utility row
            PreparedStatement stm4 = connection.prepareStatement(SQL);
            stm4.setObject(1, labelDate.getText());
            stm4.setObject(3, lblUtility.getText());
            stm4.setObject(2, txtUtility.getText());
            int res4 = stm4.executeUpdate();
            //update loan row
            PreparedStatement stm5 = connection.prepareStatement(SQL);
            stm5.setObject(1, labelDate.getText());
            stm5.setObject(3, lblLoans.getText());
            stm5.setObject(2, txtLoan.getText());
            int res5 = stm5.executeUpdate();
            //update other row
            PreparedStatement stm6 = connection.prepareStatement(SQL);
            stm6.setObject(1, labelDate.getText());
            stm6.setObject(3, lblOther.getText());
            stm6.setObject(2, txtOther.getText());
            int res6 = stm6.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Saved Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Please Calculate Total first");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String SQL = "Delete From expenses where Eid=?";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/budgetpal", "root", "1234");
            PreparedStatement stm = connection.prepareStatement(SQL);
            stm.setObject(1, txtExpenseID.getText());
            int res = stm.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Delete Success");
                txtExpenseID.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Entry not found");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewExpenses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewExpenses.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExpenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcTot;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton exitButton;
    private javax.swing.JTable expensesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAddExpense;
    private javax.swing.JLabel labelAnalitics;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelHome;
    private javax.swing.JLabel labelLogout;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblLoans;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblStationary;
    private javax.swing.JLabel lblTransportation;
    private javax.swing.JLabel lblUtility;
    private javax.swing.JButton reload;
    private javax.swing.JTextField txtExpenseID;
    private javax.swing.JTextField txtFood;
    private javax.swing.JTextField txtLoan;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtStationary;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTransport;
    private javax.swing.JTextField txtUtility;
    // End of variables declaration//GEN-END:variables
}
